version: '3.8'

services:
  # PostgreSQL Service
  postgres:
    restart: always
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  # SMTP Mail Catcher
  mailpit:
    image: axllent/mailpit:v1.15
    restart: always
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI port
